/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.server;

import java.io.IOException;
import java.util.Scanner;

public class App {
  public static void main(String[] args) throws IOException, ClassNotFoundException, InterruptedException {
    int playerNum = 0;
    int listenPort = 0;
    String hostMasterIP;
    Scanner in = new Scanner(System.in);
    while (true) {
      try {
        System.out.println("Please enter player number:");
        playerNum = Integer.parseInt(in.nextLine());
        if (playerNum >= 2 && playerNum <= 5) {
          break;
        }
        System.out.println("INVALID INPUT, TRY AGAIN");
      } catch (Exception exp) {
        System.out.println("INVALID INPUT, TRY AGAIN");
      }
    }
    while (true) {
      try {
        System.out.println("Please enter HostMaster IP:");
        hostMasterIP = in.nextLine();
        if (hostMasterIP.length() >= 1) {
          break;
        }
        System.out.println("INVALID INPUT, TRY AGAIN");
      } catch (Exception exp) {
        System.out.println("INVALID INPUT, TRY AGAIN");
      }
    }
    while (true) {
      try {
        System.out.println("Please enter listening port:");
        listenPort = Integer.parseInt(in.nextLine());
        if (listenPort > 0) {
          break;
        }
        System.out.println("INVALID INPUT, TRY AGAIN");
      } catch (Exception exp) {
        System.out.println("INVALID INPUT, TRY AGAIN");
      }
    }


    
    in.close();            
    Server server = new Server(listenPort, playerNum); // port num & player num & HMIP
    server.setHMIP(hostMasterIP);
    server.connectToHostMaster();
    server.sendGameInfo();
    server.connectToPlayer();
    
  }  
}
