/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.client;
import java.io.IOException;
import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    MainController mainController = new MainController();
    mainController.start();
  }
}
