/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.hostmaster;

public class App {
    public static void main(String[] args) {


      
      /* normal start */
      int hmPort = 8888;
      try {
        HostMaster hm = new HostMaster(hmPort);
        hm.process();
      }
      catch(Exception exp) {
        exp.printStackTrace();
      }
    }
}
