/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.client;
import java.io.IOException;
import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    Scanner in = new Scanner(System.in);
    String playerName;
    String serverIP;        
    while (true) {
      try{
        System.out.println("Please type in player name:");
        playerName = in.nextLine();
        if(playerName.length() < 1){
          throw new Exception("Invalid player name. Please try again");
        }
      
        System.out.println("Please type in server IP:");
        serverIP = in.nextLine();
        if(playerName.length() < 1){
          throw new Exception("Server IP cannot be empty. Please try again");
        }
      
        break;
      }
      catch(Exception e){
        System.out.println(e.getMessage());
      }
    }
    try{
      Client client = new Client(playerName, 12345, System.in, serverIP);
      client.play();
      in.close();
    }
    catch (IOException e){
      System.out.println("Error occured: " + e.getMessage());
    }
  }
}
