/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.server;

import java.io.IOException;
import java.util.Scanner;

public class App {
  public static void main(String[] args) throws IOException, ClassNotFoundException, InterruptedException {
    int playerNum = 0;    
    if(args.length > 0 ){
      System.out.println("Please enter player number:");
      playerNum = 2;
    }
    else {
      Scanner in = new Scanner(System.in);
      while (true) {
        try {
          System.out.println("Please enter player number:");
          playerNum = Integer.parseInt(in.nextLine());
          if (playerNum >= 2 && playerNum <= 5) {
            break;
          }
          System.out.println("INVALID INPUT, TRY AGAIN");
        } catch (Exception exp) {
          System.out.println("INVALID INPUT, TRY AGAIN");
        }
      }
        in.close();            
    }
    Server server = new Server(12345, playerNum); // port num and player num
    server.connectToPlayer();
    
  }  
}
